# Partial wave analysis

In [1]:
using JLD
using Plots

In [2]:
push!(LOAD_PATH,pwd()*"\\src")

3-element Array{Any,1}:
 "C:\\Users\\mikha\\AppData\\Local\\Julia-0.6.1\\local\\share\\julia\\site\\v0.6"
 "C:\\Users\\mikha\\AppData\\Local\\Julia-0.6.1\\share\\julia\\site\\v0.6"       
 "C:\\Users\\mikha\\Documents\\pwa_from_scratch\\src"                            

In [3]:
# workspace()
using DalitzPlotAnalysis
using amplitudes_compass

In [4]:
# mm = readdlm("C:\\Users\\mikha\\cernbox\\tmp\\2300.mc.txt");

In [5]:
function precalculate_compass_basis(fin,fout)
    mm = readdlm(fin);
    m2 = [COMPASS_wave(i,mm[e,:]...) for e=1:size(mm,1), i=1:88];
#     writedlm(fout*".re", real(m2))
#     writedlm(fout*".im", imag(m2))
    save(fout,"real",real(m2),"imag",imag(m2))
end
function read_precalc_basis(fname)
    ld = load(fname)
    ld["real"]+1im*ld["imag"]
end

read_precalc_basis (generic function with 1 method)

In [6]:
# @time let mm = readdlm("C:\\Users\\mikha\\cernbox\\tmp\\2300.mc.txt");
#     m2 = [COMPASS_wave(i,mm[e,:]...) for e=1:size(mm,1), i=1:88];
#     writedlm("mc.re.txt", real(m2))
#     writedlm("mc.im.txt", imag(m2))
# end

In [7]:
# @time precalculate_compass_basis("C:\\Users\\mikha\\cernbox\\tmp\\2300.mc.txt", "mc.jld")
# @time precalculate_compass_basis("C:\\Users\\mikha\\cernbox\\tmp\\2300.rd.txt", "rd.jld")

In [8]:
const MC = read_precalc_basis("mc.jld");

In [9]:
@time sum_mat = [sum(MC[e,i]'*MC[e,j] for e in 1:size(MC,1)) for i=1:88, j=1:88]/size(MC,1);

 30.644407 seconds (117.64 k allocations: 5.656 MiB)


In [10]:
sum_mat_n = [sum_mat[i,j]/sqrt(sum_mat[i,i]*sum_mat[j,j]) for i=1:88, j=1:88];

In [11]:
# heatmap(real(sum_mat_n))

In [12]:
const Bmat = sum_mat;
const BF = read_precalc_basis("rd.jld")[1:1000,:]
const Nd = size(BF,1);

### Coherence matrix

In [14]:
waves = readdlm(pwd()*"/src/wavelist_formated.txt");

In [15]:
noϵ = [i==1 for i=1:size(waves[:,6],1)]
posϵ = [ϵ=="+" for ϵ in waves[:,6]]
negϵ = [ϵ=="-" for ϵ in waves[:,6]]
## decomp
sum(noϵ)+sum(posϵ)+sum(negϵ)==length(waves[:,6])
block(i) = 1*noϵ[i]+2*posϵ[i]+3*negϵ[i]

block (generic function with 1 method)

In [16]:
COH = [block(i)==block(j) for i=1:88, j=1:88];
const COHc = convert(Array{Complex{Float64},2},COH);

In [17]:
function COHsq(X::AbstractVector{Complex{Float64}})
    sum(abs2(sum(X[bl])) for bl in [noϵ,posϵ,negϵ])
end

COHsq (generic function with 1 method)

In [18]:
heatmap(COH)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAF9UlEQVR4nO3XsQ2DQBBFQbCuUEoj
cJlI5wbAoe9Jnkk3+dnT7ts25gYAf+6a5+oJj16rBwAA34k1AMSJNQDEiTUAxIk1AMSJNQDEiTUA
xIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDE
iTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxI2nwzXPH84AgLXGfqye8MhnDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBx
Yg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBx
Yg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBx
Yg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBx
Yg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBx
Yg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFi
DQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHH7Nd/z
7jD248dTAIA7PmsAiBNrAIgTawCI+wC7Dg16CejsJAAAAABJRU5ErkJggg==
" transform="translate(29, 12)"/>
 
 
 
 
 
 
 
<image width="18" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAABIAAAFsCAYAAADBkelSAAACHUlEQVR4nO2c223EMAwEqUD9V5Eu
4yOvBPpjEAwIqoCF9kU5vljnyd8KYP0QIBERN+thgAoC4qhVzqVmcw0Te7BGHLWgkk0BgdQo1yZr
lH8Q0Ca7Wxy1Ux8GKBICOhAQaT+lESQ2aD9Gbe1vgU4mAiSkRgEpk824NjnZRvsh1yj7la6N1Qi0
35ZsnWtC+yORF1pxo3zUMNcYjZTUVqMeCMFBqUFAUGeN1HRA5Ds2CKjyIEBK+xlqt8qnEUSNAiLf
+Y+lFslgTdaImkc3itmUkJpxZm+ym3XLppHwOKI0Eh5HXPt1gw2035Zs0P6x7QeT7aO2rrVAtooY
2++z33aukf8PKSutUKNN9j8C5WrUraXWL18gZ2s09mlk8DzaZPdAQvtDRk1oP/TjupMaZT+Uo8Gl
NdpPAQmpYa7pks2VFhtsOo249iMwS+3NMs5sBEbZ/qXWA/ke2AfPbIya8WEUAtJVZO3vF2g/g6Oc
2XM1AqnZkg0eRxAQtSOlRmt/s4TUVqMXQAyOcmbr5pFu1N6CPqoRJntwaXU5MrZfl+zB1MCfM6Dv
sn3n2s7sF0A6apTYGDWhRkmVVpjswa5R1Ar6etmo0cGo2a4JoXYE2n909nPJttkPltZ2/xGYbOge
LZ/9Oo2WWr/A0kI34GA7Iv/KnksNm0eDNeKo6dq/rvVAVEWoHQmHf+kumcaoBfQmArwngnON0sjX
fs7+udQgoC/rNOfnsknqIwAAAABJRU5ErkJggg==
" transform="translate(532, 12)"/>
 
 
 0 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
 
 0.6 
 
 
 0.7 
 
 
 0.8 
 
 
 0.9 
 
 
 1.0 
 
<polyline clip-path="url(#clip7600)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 550.315,375.869 550.315,375.869 556.315,375.869 550.315,375.869 550.315,339.463 556.315,339.463 550.315,339.463 550.315,303.057 556.315,303.057 550.315,303.057 
 550.315,266.651 556.315,266.651 550.315,266.651 550.315,230.246 556.315,230.246 550.315,230.246 550.315,193.84 556.315,193.84 550.315,193.84 550.315,157.434 
 556.315,157.434 550.315,157.434 550.315,121.028 556.315,121.028 550.315,121.028 550.315,84.6226 556.315,84.6226 550.315,

### Map of parameters

In [20]:
fill(0.0+0.0im,2,3)

2×3 Array{Complex{Float64},2}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im

In [21]:
const ModelBlocks = [noϵ,posϵ,negϵ,negϵ]
Trel = let vect=[]
    temp = []
    numb = []
    for bl in ModelBlocks
        push!(temp,false)
        push!(temp,[true for i=1:(sum(bl)-1)]...)
        push!(numb,collect(1:88)[bl]...)
    end 
    Trel = zeros(Complex{Float64},88,sum(temp+1))
    global Tmap = fill(0,2,sum(temp+1))
    count=1
    for (i,b) in enumerate(temp)
        Trel[numb[i],count] = 1.0;
        Tmap[1,count] = numb[i]
        count+=1
        if b
            Trel[numb[i],count] = 1.0im;
            Tmap[2,count] = numb[i];
            count+=1
        end
    end
    Trel
#     numb
end;

In [22]:
Tmap

2×186 Array{Int64,2}:
 1  2  3  0  4  0  5  0  6  0  7  0  8  …   0  85   0  86   0  87   0  88   0
 0  0  0  3  0  4  0  5  0  6  0  7  0     84   0  85   0  86   0  87   0  88

In [23]:
const TT = Trel;
const TM = Tmap;

In [30]:
function TTm(p)
    c = fill(0.0+0.0im,88)
    for i in 1:size(Tmap,2)
        Tmap[1,i]!=0 && (c[Tmap[1,i]]+=1.0*p[i])
        Tmap[2,i]!=0 && (c[Tmap[2,i]]+=1.0im*p[i])
    end
    c
end

TTm (generic function with 1 method)

In [31]:
@time for i=1:1000
    TTm(rand(size(TT,2)))
end

  0.224999 seconds (1.02 M allocations: 29.877 MiB, 9.49% gc time)


In [32]:
@time for i=1:1000
    TT*rand(size(TT,2))
end

  0.027878 seconds (3.00 k allocations: 5.966 MiB)


In [33]:
# function get_form(B)
#     @inbounds m = B.*TT;
#     @inbounds v = m'COHc*m
#     v
# end
# # @time const BFE = get_form.([BF[e,:] for e=1:size(BF,1)]);

In [34]:
function get_form(B)
    m = B.*TT;
    v = m'COHc*m
    v
end

get_form (generic function with 1 method)

In [35]:
@time const TBmatT = TT'*(Bmat.*COHc)*TT;

  4.080201 seconds (571.80 k allocations: 24.947 MiB, 0.57% gc time)


In [36]:
# sR = open("recalc1.re.bin","w+") # or "r"
# sI = open("recalc1.im.bin","w+") # or "r"
# Ar = Mmap.mmap(sR, Matrix{Float64}, (size(TT,2)*Nd, size(TT,2)));
# Am = Mmap.mmap(sI, Matrix{Float64}, (size(TT,2)*Nd, size(TT,2)));

In [37]:
# @time let d = size(TT,2)
#     for e = 1:Nd
#         matr = get_form(BF[e,:])
#         Ar[((e-1)*d+1):(e*d),:] .= real(matr)
#         Am[((e-1)*d+1):(e*d),:] .= imag(matr)        
#     end
# end

In [22]:
# function preBFE(e)
#     d = size(TT,2)
#     Ar[((e-1)*d+1):(e*d),:] .+ 1im*Am[((e-1)*d+1):(e*d),:]
# end

In [38]:
# @time for i in 1:10000
#     preBFE(i);
# end

Likelihood functions

In [39]:
function LLH(pars::Vector{Float64})
    res = sum(log(real(begin
#                     m = get_form(BF[e,:])
                    cv = BF[e,:].*(TT*pars)
                    COHsq(cv)
                    end)) for e in 1:Nd)
    - res + real(pars'*TBmatT*pars) * Nd
end
function dLLH(pars::Vector{Float64})
    resP = sum(2real(begin
                    m = get_form(BF[e,:])
                    v = m*pars
                    v / (pars'*v)
                end)  for e in 1:Nd)
    - resP + 2real(TBmatT*pars)* Nd 
end
function LLH_and_GRAD!(pars::Vector{Float64}, grad::Vector{Float64})
    val = 0.0; grad .= 0.0;
    for e in 1:Nd
        m = get_form(BF[e,:])
        v = m*pars
        sc = real(pars'*v)
        val -= log(sc)
        grad .-= (2real(v) ./ sc)
    end
#     println(val)
    BB = TBmatT*pars;
    val += real(pars'*BB) * Nd;
    grad .+= 2real(BB)* Nd;
    return val;
end

LLH_and_GRAD! (generic function with 1 method)

In [40]:
test_t = rand(size(TT,2));

In [42]:
@time LLH(test_t)

  0.047392 seconds (23.50 k allocations: 9.230 MiB)


308521.65838062385

In [45]:
@time dLLH(test_t)

  4.521957 seconds (19.50 k allocations: 1.018 GiB, 4.93% gc time)


186-element Array{Float64,1}:
   175.557 
 27875.1   
  3450.57  
  4539.24  
  6327.47  
  5640.46  
 31373.4   
 22562.3   
  -238.719 
  1282.08  
   364.573 
   270.48  
 11318.9   
     ⋮     
 39601.0   
 30854.7   
 21363.3   
 31187.3   
 17549.0   
 15605.4   
    96.0192
   -69.2139
   298.012 
   236.96  
   644.774 
   814.109 

In [46]:
using NLopt

In [47]:
minpars0 = vcat(readdlm("min.txt")...);

In [49]:
function minimize(; verbose=0)
#     function abs_inverse(x::Vector, grad::Vector) 
#         v = LLH(x)
#         if length(grad) > 0
#             grad[:] = dLLH(x)
#         end        
#         verbose==1 && println(v)
#         verbose==2 && println("\n------\n$x\n$grad\n->$v")
#         v
#     end
    function abs_inverse(x::Vector, grad::Vector) 
        if length(grad) > 0
            v = LLH_and_GRAD!(x,grad)
        else
            v = LLH(x)
        end
        verbose==1 && println(v)
        verbose==2 && println("\n------\n$x\n$grad\n->$v")
        return v;
    end

    # find minimum which of course suppose t o be zero
#     opt = Opt(:LN_COBYLA, 88)
    opt = Opt(:LN_COBYLA, size(TT,2)) # try LD_LBFGS || LD_MMA
    xtol_rel!(opt,1e-4)
#     set_maxeval(opt,500000)

    min_objective!(opt, abs_inverse)

    (minf,pars,ret) = optimize(opt, minpars0)#rand(size(TT,2)))
    println("got $minf at $pars = [m, Γ] after some iterations (returned $ret)")
    pars
end

minimize (generic function with 1 method)

In [50]:
# hcat(minpar0,minpars)

In [51]:
@time minpars = minimize(verbose=1)

-123.95425514416127
51660.936180698336
-119.23558002284483
-123.95421895891513
-123.95435552813024
-123.95439918935347
-123.9544770997959
-123.95454451978219
-123.95463186946654
-123.95470330670582
-123.95477145817347
-123.95483992266486
-123.95497668608584
-123.95510863633172
-123.95526270906635
-123.95541644493665
-123.95556096732878
-123.95568441647447
-123.95592006109291
-123.9560191925417
-123.95617789398739
-123.9563852988797
-123.95660636670402
-123.95676921099721
-123.95693567089768
-123.95706957527966
-123.95729776038377
-123.95729456680067
-123.95741768699133
-123.95756070974824
-123.9576650912702
-123.95779445187475
-123.95789650892357
-123.95801388661266
-123.95814542315532
-123.95826532498393
-123.95849989634382
-123.95868942292168
-123.95884735248512
-123.95899821878334
-123.95912961950899
-123.9594036763666
-123.95967672474342
-123.95992906070853
-123.96023507810128
-123.96042157727652
-123.96062427532524
-123.96078441226746
-123.9609226901274
-123.96131462790663
-123.96

186-element Array{Float64,1}:
  4.64303e-170
 -0.0259743   
 -0.0537772   
  0.177909    
  0.0042875   
  0.0307898   
 -0.0252816   
 -0.0410422   
  0.185862    
 -0.121763    
 -0.311717    
  0.0196083   
 -0.0232782   
  ⋮           
  0.131441    
 -0.125191    
  0.0211064   
 -0.453196    
 -0.0873311   
  0.244261    
 -0.377791    
  0.167059    
 -0.110394    
  0.0830113   
 -0.217548    
 -0.269908    

In [125]:
@time minpars2 = minimize(verbose=1)

1985.6664735858049
2.545538699031223e13
2.5463758591544294e9
244231.61305025243
1735.9946015188343
1815.056597819199
1611.2839737045306
1533.4917685024902
1443.0401155377403
1387.5537194460467
1342.4531660343437
1306.373855693575
1274.94897115582
1348.0614679457867
1235.037570893297
1201.0837915566517
1172.1819448585848
1148.6675308011472
1123.5731329235114
1093.895893837178
1071.005482047538
1051.6170285032313
1031.9907272618384
1011.937012399032
991.6654161120823
977.0672867494777
965.3305501621289
957.9418935001995
946.1790157981886
936.8134814615441
927.0641843046324
913.0655257620438
899.2983625612615
884.0393958211534
872.8886446277738
864.425013694161
860.473356879771
852.9020156152783
846.0303376622614
838.0854593360527
829.4465442206983
821.1319878807972
815.5100258219791
808.7673494110986
802.1643914148717
796.902895553947
791.2391120320481
784.035398039694
772.6475671366024
764.7038600845644
756.035074968926
749.4456683983608
745.2630464903959
739.1387479707319
729.021757077

487.56412053817803
487.56397394222586
487.5638446271387
487.56372634456056
487.5635755206131
487.5634324256316
487.56327208454786
487.5631192453966
487.5629780804502
487.5627984495095
487.5625436740738
487.56215008737126
487.56162145161943
487.56108977326767
487.56061367201073
487.56007056616545
487.5593673246385
487.55851586764584
487.55760824169374
487.55663987956177
487.555550042769
487.5542695136919
487.55328719432146
487.5524862831353
487.55145835123403
487.55001022657234
487.54780549311
487.5455184816037
487.54352121464035
487.54148834071566
487.53882349848936
487.5356775018772
487.53353003398115
487.53233968487075
487.53140513526523
487.53017032444586
487.52860622039043
487.527233922121
487.52601624853196
487.5249185461016
487.52389389611017
487.5231262977668
487.5225914865787
487.522151675008
487.52167842281233
487.5214010740656
487.5212989757856
487.5212328581347
487.5211516044892
487.5210523651276
487.5209712888809
487.52091009346805
487.5208584568354
487.5207993377335
487.52

186-element Array{Float64,1}:
 -5.96031e-35
 -0.0332271  
 -0.0491032  
  0.0352418  
 -0.0722667  
  0.000656321
  0.0310938  
 -0.0428372  
  0.121539   
 -0.0329123  
 -0.11297    
 -0.137733   
 -0.0210682  
  ⋮          
  0.136467   
 -0.143576   
 -0.00213442 
 -0.464127   
 -0.0847298  
  0.240082   
 -0.282778   
  0.207908   
 -0.101294   
 -0.130073   
 -0.139424   
 -0.253787   

In [126]:
const MCD = readdlm("C:\\Users\\mikha\\cernbox\\tmp\\2300.mc.txt");

In [131]:
@time weights = let mpars = TT*minpars2
    [real(begin
                v = MC[i,:].*mpars
                v'*COH*v
                end) for i in 1:size(MC,1)];
    end;

 10.771764 seconds (5.18 M allocations: 2.468 GiB, 1.61% gc time)


In [132]:
histogram(sqrt.(MCD[:,2]), weights=weights, bins=(linspace(0.3,2.2,100)))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 0 
 
 
 2500 
 
 
 5000 
 
 
 7500 
 
 
 10000 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [133]:
DT = readdlm("C:\\Users\\mikha\\cernbox\\tmp\\2300.rd.txt");

In [134]:
stephist(sqrt.(MCD[:,2]), weights=weights/size(MCD,1)*size(DT,1),
    bins=linspace(0.3,2.2,100),lab="weighted MC")
stephist!(sqrt.(DT[:,2]), bins=linspace(0.3,2.2,100),lab="data") 

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 0 
 
 
 500 
 
 
 1000 
 
 
 1500 
 
 
 2000 
 
<polyline clip-path="url(#clip0602)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 42.5104,375.869 42.5104,359.932 47.9427,359.932 47.9427,353.486 53.3751,353.486 53.3751,352.48 58.8075,352.48 58.8075,345.479 64.2398,345.479 64.2398,344.835 
 69.6722,344.835 69.6722,341.438 75.1046,341.438 75.1046,332.023 80.537,332.023 80.537,326.825 85.9693,326.825 85.9693,325.351 91.4017,325.351 91.4017,322.002 
 96.8341,322.002 96.8341,314.397 102.266,314.397 102.266,308.161 107.699,308.161 107.699,303.595 113.131,303.595 113.131,299.025 118.564,299.025 118.564,295.187 
 123.996,295.187 123.996,287.651 129.428,287.651 129.428,271.06 134.861,271.06 134.861,273.856 140.293,273.856 140.293,250.391 145.725,250.391 145.725,227.108 
 151.158,227.108 151.158,214.362 156.59,214.362 156.59,188.71 162.023,188.71 162.023,140.52 167.455,140.52 167.455,93.4565 172.887,93.4565 172.887,62.9839 
 178.32,62.9839 178.32,69.3383 183.752,69.3383 183.752,104.633 189.184,104.633 189.184,129.784 194.617,129.784 194.617,175.086 200.049,175.086 200.049,201.368 
 205.481,201.368 205.481,206.224 210.914,206.224 210.914,212.95 216.346,212.95 216.346,239.396 221.779,239.396 221.779,232.72 227.211,232.72 227.211,229.203 
 232.643,229.203 232.643,232.921 238.076,232.921 238.076,257.792 243.508,257.792 243.508,243.62 248.94,243.62 248.94,233.202 254.373,233.202 254.373,238.043 
 259.805,238.043 259.805,233.316 265.238,233.316 265.238,224.086 270.67,224.086 270.67,230.414 276.102,230.414 276.102,224.283 281.535,224.283 281.535,209.461 
 286.967,209.461 286.967,204.394 292.399,204.394 292.399,190.715 297.832,190.715 297.832,180.374 303.264,180.374 303.264,171.13 308.696,171.13 308.696,162.447 
 314.129,162.447 314.129,159.22 319.561,159.22 319.561,165.464 324.994,165.464 324.994,176.758 330.426,176.758 330.426,189.431 335.858,189.431 335.858,209.308 
 341.291,209.308 341.291,226.3 346.723,226.3 346.723,235.263 352.155,235.263 352.155,243.607 357.588,243.607 357.588,244.485 363.02,244.485 363.02,249.688 
 368.453,249.688 368.453,249.46 373.885,249.46 373.885,252.333 379.317,252.333 379.317,256.775 384.75,256.775 384.75,254.863 390.182,254.863 390.182,254.863 
 395.614,254.863 395.614,249.305 401.047,249.305 401.047,255.208 406.479,255.208 406.479,245.235 411.912,245.235 411.912,237.398 417.344,237.398 417.344,232.835 
 422.776,232.835 422.776,227.586 428.209,227.586 428.209,225.53 433.641,225.53 433.641,230.185 439.073,230.185 439.073,229.536 444.506,229.536 444.506,216.929 
 449.938,216.929 449.938,221.138 455.37,221.138 455.37,218.915 460.803,218.915 460.803,225.741 466.235,225.741 466.235,214.987 471.668,214.987 471.668,213.121 
 477.1,213.121 477.1,219.976 482.532,219.976 482.532,220.51 487.965,220.51 487.965,224.158 493.397,224.158 493.397,229.867 498.829,229.867 498.829,238.27 
 504.262,238.27 504.262,236.91 509.694,236.91 509.694,237.693 515.127,237.693 515.127,249.067 520.559,249.067 520.559,257.31 525.991,257.31 525.991,245.752 
 531.424,245.752 531.424,248.89 536.856,248.89 536.856,247.412 542.288,247.412 542.288,253.993 547.721,253.993 547.721,270.767 553.153,270.767 553.153,264.839 
 558.585,264.839 558.585,311.321 564.018,311.321 564.018,344.695 569.45,344.695 569.45,373.81 574.883,373.81 574.883,375.869 580.315,375.869 
 "/>
<polyline clip-path="url(#clip0602)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 42.5104,375.869 42.5104,357.625 47.9427,357.625 47.9427,351.11 53.3751,351.11 53.3751,347.037 58.8075,347.037 58.8075,339.381 64.2398,339.381 64.2398,334.821 
 69.6722,334.821 69.6722,331.563 75.1046,331.563 75.1046,327.816 80.537,327.816 80.537,318.857 85.9693,318.857 85.9693,311.527 91.4017,311.527 91.4017,301.265 
 96.8341,301.265 96.8341,305.012 102.266,305.012 102.266,297.845 107.699,297.

In [135]:
stephist(MCD[:,3], weights=weights/size(MCD,1)*size(DT,1),
    bins=linspace(-1,1,100),lab="weighted MC")
stephist!(DT[:,3], bins=linspace(-1,1,100),lab="data") 

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 0 
 
 
 1000 
 
 
 2000 
 
 
 3000 
 
 
 4000 
 
 
 5000 
 
 
 6000 
 
<polyline clip-path="url(#clip0802)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 42.5104,375.869 42.5104,156.457 47.9427,156.457 47.9427,193.086 53.3751,193.086 53.3751,227.089 58.8075,227.089 58.8075,261.651 64.2398,261.651 64.2398,280.345 
 69.6722,280.345 69.6722,300.25 75.1046,300.25 75.1046,312.104 80.537,312.104 80.537,319.061 85.9693,319.061 85.9693,327.154 91.4017,327.154 91.4017,332.818 
 96.8341,332.818 96.8341,336.267 102.266,336.267 102.266,338.973 107.699,338.973 107.699,342.43 113.131,342.43 113.131,342.166 118.564,342.166 118.564,343.427 
 123.996,343.427 123.996,344.3 129.428,344.3 129.428,343.198 134.861,343.198 134.861,343.191 140.293,343.191 140.293,344.721 145.725,344.721 145.725,342.383 
 151.158,342.383 151.158,344.293 156.59,344.293 156.59,343.175 162.023,343.175 162.023,343.509 167.455,343.509 167.455,342.091 172.887,342.091 172.887,343.307 
 178.32,343.307 178.32,344.239 183.752,344.239 183.752,344.591 189.184,344.591 189.184,345.753 194.617,345.753 194.617,347.058 200.049,347.058 200.049,343.421 
 205.481,343.421 205.481,345.374 210.914,345.374 210.914,346.433 216.346,346.433 216.346,344.743 221.779,344.743 221.779,345.624 227.211,345.624 227.211,344.821 
 232.643,344.821 232.643,347.76 238.076,347.76 238.076,345.904 243.508,345.904 243.508,346.52 248.94,346.52 248.94,345.404 254.373,345.404 254.373,345.721 
 259.805,345.721 259.805,345.916 265.238,345.916 265.238,345.706 270.67,345.706 270.67,344.671 276.102,344.671 276.102,347.026 281.535,347.026 281.535,348.204 
 286.967,348.204 286.967,345.242 292.399,345.242 292.399,342.879 297.832,342.879 297.832,347.152 303.264,347.152 303.264,348.032 308.696,348.032 308.696,344.029 
 314.129,344.029 314.129,347.828 319.561,347.828 319.561,348.024 324.994,348.024 324.994,346.55 330.426,346.55 330.426,347.769 335.858,347.769 335.858,347.972 
 341.291,347.972 341.291,351.279 346.723,351.279 346.723,346.015 352.155,346.015 352.155,348.324 357.588,348.324 357.588,350.408 363.02,350.408 363.02,349.234 
 368.453,349.234 368.453,347.06 373.885,347.06 373.885,345.464 379.317,345.464 379.317,345.416 384.75,345.416 384.75,343.166 390.182,343.166 390.182,346.568 
 395.614,346.568 395.614,349.308 401.047,349.308 401.047,343.768 406.479,343.768 406.479,344.843 411.912,344.843 411.912,345.2 417.344,345.2 417.344,344.053 
 422.776,344.053 422.776,342.353 428.209,342.353 428.209,339.947 433.641,339.947 433.641,340.843 439.073,340.843 439.073,339.448 444.506,339.448 444.506,338.042 
 449.938,338.042 449.938,338.548 455.37,338.548 455.37,336.378 460.803,336.378 460.803,333.557 466.235,333.557 466.235,335.461 471.668,335.461 471.668,336.24 
 477.1,336.24 477.1,334.434 482.532,334.434 482.532,334 487.965,334 487.965,332.505 493.397,332.505 493.397,333.49 498.829,333.49 498.829,331.834 
 504.262,331.834 504.262,325.673 509.694,325.673 509.694,324.824 515.127,324.824 515.127,320.842 520.559,320.842 520.559,317.119 525.991,317.119 525.991,307.854 
 531.424,307.854 531.424,306.328 536.856,306.328 536.856,300.043 542.288,300.043 542.288,292.862 547.721,292.862 547.721,272.011 553.153,272.011 553.153,268.41 
 558.585,268.41 558.585,243.774 564.018,243.774 564.018,225.809 569.45,225.809 569.45,197.935 574.883,197.935 574.883,128.6 580.315,128.6 580.315,375.869 
 
 "/>
<polyline clip-path="url(#clip0802)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 42.5104,375.869 42.5104,110.432 47.9427,110.432 47.9427,134.357 53.3751,134.357 53.3751,190.021 58.8075,190.021 58.8075,224.924 64.2398,224.924 64.2398,256.962 
 69.6722,256.962 69.6722,282.14 75.1046,282.14 75.1046,295.385 80.537,295.385 80.537,312.687 85.9693,312.687 85.9693,317.34 91.4017,317.34 91.4017,323.068 
 96.8341,323.0